
service: challenge-serverless

package:
  example:
    - layer/**

layers:
  LayerDependecies:
    path: layer
    description: "requirements layer"

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - 'arn:aws:sns:us-east-1:131167460192:requests-topic'
    - Effect: 'Allow'
      Action:
        - "sqs:ReceiveMessage"
      Resource:
        - 'arn:aws:sqs:us-east-1:131167460192:requests-queue'
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::final-challenge-bucket/*"

stage: production
functions:
  create:
    handler: create.handler
    layers:
      - {Ref: LayerDependeciesLambdaLayer}
    events:
      - http:
          path: create
          method: post
          cors: true
  sell:
    handler: sell.handler
    layers:
      - {Ref: LayerDependeciesLambdaLayer}
    events:
      - http:
          path: sell
          method: post
          cors: true
  bucket:
    handler: bucket.handler
    events:
      - sqs: 'arn:aws:sqs:us-east-1:131167460192:requests-queue'
