
service: challenge-serverless

provider:
  name: aws
  runtime: python3.7

stage: production
functions:
  create:
    handler: create.handler
    events:
      - http:
          path: create/{name}/{id}/{price}
          method: post
          cors: true
  sell:
    handler: sell.handler
    events:
      - http:
          path: sell/{id}/{customer}
          method: post
          cors: true
